CREATE TABLE IF NOT EXISTS sip_extensions (
  id SERIAL PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(128) NOT NULL,
  display_name VARCHAR(128),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inbound_routes (
  id SERIAL PRIMARY KEY,
  did VARCHAR(32) NOT NULL UNIQUE,
  flow_id INTEGER NOT NULL REFERENCES call_flows(id) ON DELETE CASCADE,
  label VARCHAR(128),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
