import { Test, TestingModule } from "@nestjs/testing";
import { AsteriskConfigService } from "./asterisk-config.service";
import { SipExtensionEntity } from "../extensions/entities/sip-extension.entity";
import { SipTrunkEntity } from "../trunks/entities/sip-trunk.entity";
import { VpnService } from "../vpn/vpn.service";
import { getRepositoryToken } from "@nestjs/typeorm";
import { DataSource } from "typeorm";

import { promises as fsPromises } from "fs";

describe("AsteriskConfigService", () => {
  let service: AsteriskConfigService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AsteriskConfigService,
        {
          provide: getRepositoryToken(SipExtensionEntity),
          useValue: { find: jest.fn().mockResolvedValue([]) },
        },
        {
          provide: getRepositoryToken(SipTrunkEntity),
          useValue: { find: jest.fn().mockResolvedValue([]) },
        },
        { provide: DataSource, useValue: { query: jest.fn() } },
        {
          provide: VpnService,
          useValue: {
            getRelayStatus: jest.fn().mockResolvedValue({
              active: false,
              handshakeEstablished: false,
              vpsPublicIp: null,
            }),
            getStatus: jest.fn(),
            listPeers: jest.fn(),
            createPeer: jest.fn(),
            getPeerConfig: jest.fn(),
            getPeerQr: jest.fn(),
            revokePeer: jest.fn(),
            removeVpn: jest.fn(),
            getRelayGuide: jest.fn(),
            createRelayConfig: jest.fn(),
            activateRelayTunnel: jest.fn(),
            deactivateRelayTunnel: jest.fn(),
            getRelayStatusResponse: jest.fn(),
            getRelayConfig: jest.fn(),
          },
        },
      ],
    }).compile();

    service = module.get<AsteriskConfigService>(AsteriskConfigService);
    jest.spyOn(service as any, "runPythonScript").mockResolvedValue("{}");
    jest.spyOn(fsPromises, "writeFile").mockResolvedValue(undefined);
    jest.spyOn(fsPromises, "mkdir").mockResolvedValue(undefined);
    jest.spyOn(fsPromises, "readFile").mockResolvedValue("");
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it("generatePjsipConfig with extensions produces [endpoint/XXXX] sections with correct auth and aor blocks", () => {
    const ext = {
      username: "1000",
      password: "pwd",
      transport: "transport-udp",
      endpointFlags: [],
    };
    const config = (service as any).buildExtensionsConfig([ext], null);
    expect(config).toContain("[1000]");
    expect(config).toContain("type = endpoint");
    expect(config).toContain("[1000-auth]");
    expect(config).toContain("password = pwd");
  });

  it("generatePjsipConfig with empty list returns only the global transport section", () => {
    const config = (service as any).buildExtensionsConfig([], null);
    expect(config.trim()).toBe(
      "; auto-generated by callytics — do not edit manually",
    );
  });

  it("generateTrunkConfig with digest trunk produces registration and endpoint section", () => {
    const trunk = {
      id: 1,
      name: "t1",
      host: "provider.com",
      port: 5060,
      username: "user",
      password: "secret",
      providerPreset: "generic",
      enabled: true,
    } as SipTrunkEntity;
    const config = (service as any).buildTrunksConfig([trunk]);
    expect(config).toContain("[trunk-1]");
    expect(config).toContain("[trunk-1-reg]");
    expect(config).toContain("type = registration");
    expect(config).toContain("server_uri = sip:provider.com");
  });

  it("buildInboundRoutesConfig always includes direct outbound dial pattern", () => {
    const content = (service as any).buildInboundRoutesConfig([
      { did: '1234' },
    ]);

    expect(content).toContain('exten => _#.,1,Stasis(callytics)');
    expect(content).toContain('exten => _#.,n,Hangup()');
    expect(content).toContain('exten => 1234,1,Stasis(callytics)');
  });

  it("AMI reload command is called after config is written", async () => {
    const spyWrite = jest
      .spyOn(service, "writeExtensionsConfig")
      .mockResolvedValue();
    const spyReload = jest
      .spyOn(service as any, "sendAmiCommand")
      .mockResolvedValue(undefined);

    await service.syncExtensions([]);

    expect(spyWrite).toHaveBeenCalled();
    expect(spyReload).toHaveBeenCalledWith("module reload res_pjsip.so");
  });

  it("syncUdpTransport rewrites the transport block and reloads pjsip", async () => {
    const amiSpy = jest
      .spyOn(service as any, "sendAmiCommand")
      .mockResolvedValue(undefined);

    await service.syncUdpTransport("203.0.113.10");

    expect(fsPromises.writeFile).toHaveBeenCalledWith(
      expect.stringContaining("pjsip_relay.conf"),
      "; auto-generated relay settings \u2014 do not commit\n; external_* values come from the active relay/VPS public IP at runtime.\n; endpoint NAT overrides are loaded from pjsip_extensions_relay.conf.\n\nexternal_signaling_address = 203.0.113.10\nexternal_media_address = 203.0.113.10\nlocal_net = 172.16.0.0/12\nlocal_net = 127.0.0.1/32\nlocal_net = 10.20.0.0/16\nlocal_net = 10.8.0.0/24\n\n#include pjsip_extensions_relay.conf\n",
      "utf8",
    );
    // pjsip.conf must never be written to during a relay sync
    const allWritePaths = (fsPromises.writeFile as jest.Mock).mock.calls.map(
      (call: unknown[]) => call[0],
    );
    expect(allWritePaths.every((p: string) => !p.endsWith('pjsip.conf'))).toBe(true);
    expect(amiSpy).toHaveBeenCalledWith("pjsip reload");
  });

  it("syncUdpTransport with null clears the relay config", async () => {
    const amiSpy = jest
      .spyOn(service as any, "sendAmiCommand")
      .mockResolvedValue(undefined);

    await service.syncUdpTransport(null);

    expect(fsPromises.writeFile).toHaveBeenCalledWith(
      expect.stringContaining("pjsip_relay.conf"),
      "; auto-generated relay settings \u2014 do not commit\n; external_* values come from the active relay/VPS public IP at runtime.\n; endpoint NAT overrides are loaded from pjsip_extensions_relay.conf.\n\n#include pjsip_extensions_relay.conf\n",
      "utf8",
    );
    // pjsip.conf must never be written to during a relay sync
    const allWritePaths = (fsPromises.writeFile as jest.Mock).mock.calls.map(
      (call: unknown[]) => call[0],
    );
    expect(allWritePaths.every((p: string) => !p.endsWith('pjsip.conf'))).toBe(true);
    expect(amiSpy).toHaveBeenCalledWith("pjsip reload");
  });

  it("syncExtensionsRelayConfig rewrites endpoint NAT overrides with the live external address", async () => {
    const extensionsRepository = (service as any).extensionsRepository;
    extensionsRepository.find.mockResolvedValue([{ username: "1000" }]);

    await service.syncExtensionsRelayConfig("203.0.113.10");

    expect(fsPromises.writeFile).toHaveBeenCalledWith(
      expect.stringContaining("pjsip_extensions_relay.conf"),
      "; auto-generated NAT overrides \u2014 do not commit\n\n; media_address values come from the active relay/VPS public IP at runtime.\n\n\n\n[1000](+)\nmedia_address = 203.0.113.10\nrtp_symmetric = yes\n",
      "utf8",
    );
  });

  it("syncExtensionsRelayConfig writes only the header when relay is inactive", async () => {
    const extensionsRepository = (service as any).extensionsRepository;
    extensionsRepository.find.mockResolvedValue([{ username: "1000" }]);

    await service.syncExtensionsRelayConfig(null);

    expect(fsPromises.writeFile).toHaveBeenCalledWith(
      expect.stringContaining("pjsip_extensions_relay.conf"),
      "; auto-generated NAT overrides — do not commit\n; media_address values come from the active relay/VPS public IP at runtime.\n",
      "utf8",
    );
  });

  it("if AMI reload throws, the error is caught and not swallowed silently", async () => {
    jest.spyOn(service, "writeExtensionsConfig").mockResolvedValue();
    jest
      .spyOn(service as any, "sendAmiCommand")
      .mockRejectedValue(new Error("AMI dead"));
    const loggerSpy = jest
      .spyOn((service as any).logger, "error")
      .mockImplementation(() => {});

    await expect(service.syncExtensions([])).resolves.not.toThrow();
    expect(loggerSpy).toHaveBeenCalledWith(
      expect.stringContaining("failed"),
      expect.stringContaining("AMI dead"),
    );
  });
});
