import { Injectable, Logger } from '@nestjs/common';
import { spawn } from 'child_process';
import { promises as fs } from 'fs';
import { join } from 'path';
import { InboundRouteEntity } from '../inbound-routes/entities/inbound-route.entity';
import { SipExtensionEntity } from '../extensions/entities/sip-extension.entity';

@Injectable()
export class AsteriskConfigService {
  private readonly logger = new Logger(AsteriskConfigService.name);
  private readonly configDir = process.env.ASTERISK_CONFIG_DIR || '/etc/asterisk';
  private readonly amiHost = process.env.AMI_HOST || '127.0.0.1';
  private readonly amiPort = Number(process.env.AMI_PORT || 5038);
  private readonly amiUser = process.env.AMI_USER || 'callytics';
  private readonly amiPassword = process.env.AMI_PASSWORD || process.env.AMI_PASS || 'callytics';

  async syncExtensions(extensions: SipExtensionEntity[]): Promise<void> {
    await fs.mkdir(this.configDir, { recursive: true });
    await this.ensurePjsipTemplate();
    await this.ensureIncludeAtFileStart(join(this.configDir, 'pjsip.conf'), '#include pjsip_callytics_extensions.conf');
    await fs.writeFile(join(this.configDir, 'pjsip_callytics_extensions.conf'), this.buildExtensionsConfig(extensions), 'utf8');
    await this.sendAmiCommand('module reload res_pjsip.so');
  }

  async syncInboundRoutes(routes: InboundRouteEntity[]): Promise<void> {
    await fs.mkdir(this.configDir, { recursive: true });
    await this.ensureIncludeAtFileEnd(join(this.configDir, 'extensions.conf'), '#include extensions_callytics_inbound.conf');
    await fs.writeFile(join(this.configDir, 'extensions_callytics_inbound.conf'), this.buildInboundRoutesConfig(routes), 'utf8');
    await this.sendAmiCommand('dialplan reload');
  }

  private buildExtensionsConfig(extensions: SipExtensionEntity[]): string {
    const blocks = extensions.map((extension) => [
      `[${extension.username}]`,
      'type = aor',
      'max_contacts = 5',
      'remove_unavailable = yes',
      '',
      `[${extension.username}-auth]`,
      'type = auth',
      'auth_type = userpass',
      `username = ${extension.username}`,
      `password = ${extension.password}`,
      '',
      `[${extension.username}]`,
      'type = endpoint',
      'transport = transport-udp',
      'context = callytics-inbound',
      'disallow = all',
      'allow = ulaw',
      'allow = alaw',
      'direct_media = no',
      'force_rport = yes',
      'rewrite_contact = yes',
      `auth = ${extension.username}-auth`,
      `aors = ${extension.username}`,
    ].join('\n'));

    return ['; auto-generated by callytics — do not edit manually', '', ...blocks].join('\n\n').trimEnd() + '\n';
  }

  private buildInboundRoutesConfig(routes: InboundRouteEntity[]): string {
    const lines: string[] = ['; auto-generated by callytics — do not edit manually', '', '[callytics-inbound]'];
    for (const route of routes) {
      lines.push(`exten => ${route.did},1,Stasis(callytics)`);
      lines.push(`exten => ${route.did},n,Hangup()`);
      lines.push('');
    }
    return lines.join('\n').trimEnd() + '\n';
  }

  private async ensureIncludeAtFileStart(filePath: string, includeLine: string): Promise<void> {
    let content = '';
    try {
      content = await fs.readFile(filePath, 'utf8');
    } catch {
      content = '';
    }

    const lines = content
      .split(/\r?\n/)
      .filter((line) => line.trim() !== includeLine.trim());

    while (lines.length > 0 && lines[0].trim() === '') {
      lines.shift();
    }

    const body = lines.join('\n');
    const next = body
      ? `${includeLine}\n\n${body.replace(/^\n+/, '')}`
      : `${includeLine}\n`;

    await fs.writeFile(filePath, next.endsWith('\n') ? next : `${next}\n`, 'utf8');
  }

  private async ensureIncludeAtFileEnd(filePath: string, includeLine: string): Promise<void> {
    let content = '';
    try {
      content = await fs.readFile(filePath, 'utf8');
    } catch {
      content = '';
    }

    const lines = content
      .split(/\r?\n/)
      .filter((line) => line.trim() !== includeLine.trim());

    while (lines.length > 0 && lines[lines.length - 1].trim() === '') {
      lines.pop();
    }

    const body = lines.join('\n');
    const next = body
      ? `${body}\n\n${includeLine}\n`
      : `${includeLine}\n`;

    await fs.writeFile(filePath, next, 'utf8');
  }

  private async ensurePjsipTemplate(): Promise<void> {
    const filePath = join(this.configDir, 'pjsip.conf');
    let content = '';
    try {
      content = await fs.readFile(filePath, 'utf8');
    } catch {
      content = '';
    }

    if (content.includes('[callytics-endpoint-template]')) {
      return;
    }

    const templateBlock = [
      '',
      '[callytics-endpoint-template](!)',
      'type = endpoint',
      'transport = transport-udp',
      'context = callytics-inbound',
      'disallow = all',
      'allow = ulaw',
      'allow = alaw',
      'direct_media = no',
      'force_rport = yes',
      'rewrite_contact = yes',
      '',
    ].join('\n');

    await fs.writeFile(filePath, `${content.trimEnd()}${templateBlock}`, 'utf8');
  }

  private async sendAmiCommand(command: string): Promise<void> {
    const script = [
      'import socket, sys, time',
      'host, port, user, password, command = sys.argv[1:6]',
      'port = int(port)',
      'sock = socket.create_connection((host, port), timeout=5)',
      'sock.settimeout(2)',
      'sock.recv(4096)',
      "sock.sendall(f'Action: Login\\r\\nUsername: {user}\\r\\nSecret: {password}\\r\\n\\r\\n'.encode())",
      'login = sock.recv(4096).decode(errors="replace")',
      "if 'Authentication accepted' not in login:",
      '    raise SystemExit(login)',
      "sock.sendall(f'Action: Command\\r\\nActionID: cmd-1\\r\\nCommand: {command}\\r\\n\\r\\n'.encode())",
      'deadline = time.time() + 2',
      'response = ""',
      'while time.time() < deadline:',
      '    try:',
      '        chunk = sock.recv(4096).decode(errors="replace")',
      '        if not chunk:',
      '            break',
      '        response += chunk',
      "        if 'Response: Error' in response:",
      '            raise SystemExit(response)',
      "        if 'Message: Command output follows' in response or '--END COMMAND--' in response or 'Response: Success' in response:",
      '            break',
      '    except TimeoutError:',
      '        break',
      "sock.sendall(b'Action: Logoff\\r\\n\\r\\n')",
      'try:',
      '    sock.recv(4096)',
      'except TimeoutError:',
      '    pass',
      'sock.close()',
    ].join('\n');

    await new Promise<void>((resolve, reject) => {
      const child = spawn('python3', ['-c', script, this.amiHost, String(this.amiPort), this.amiUser, this.amiPassword, command]);
      let stderr = '';
      let stdout = '';

      child.stdout.on('data', (chunk) => {
        stdout += chunk.toString();
      });
      child.stderr.on('data', (chunk) => {
        stderr += chunk.toString();
      });
      child.on('error', reject);
      child.on('close', (code) => {
        if (code === 0) {
          resolve();
          return;
        }
        reject(new Error(`AMI command failed (${command}) stdout=${stdout} stderr=${stderr}`));
      });
    });

    this.logger.log(`AMI command executed: ${command}`);
  }
}
