import { Test, TestingModule } from '@nestjs/testing';
import { AsteriskConfigService } from './asterisk-config.service';
import { SipExtensionEntity } from '../extensions/entities/sip-extension.entity';
import { SipTrunkEntity } from '../trunks/entities/sip-trunk.entity';
import { getRepositoryToken } from '@nestjs/typeorm';
import { DataSource } from 'typeorm';

import { promises as fsPromises } from 'fs';

describe('AsteriskConfigService', () => {
  let service: AsteriskConfigService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AsteriskConfigService,
        { provide: getRepositoryToken(SipExtensionEntity), useValue: { find: jest.fn().mockResolvedValue([]) } },
        { provide: getRepositoryToken(SipTrunkEntity), useValue: { find: jest.fn().mockResolvedValue([]) } },
        { provide: DataSource, useValue: { query: jest.fn() } },
      ],
    }).compile();

    service = module.get<AsteriskConfigService>(AsteriskConfigService);
    jest.spyOn(service as any, 'runPythonScript').mockResolvedValue('{}');
    jest.spyOn(fsPromises, 'writeFile').mockResolvedValue(undefined);
    jest.spyOn(fsPromises, 'mkdir').mockResolvedValue(undefined);
    jest.spyOn(fsPromises, 'readFile').mockResolvedValue('');
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('generatePjsipConfig with extensions produces [endpoint/XXXX] sections with correct auth and aor blocks', () => {
    const ext = { username: '1000', password: 'pwd' } as SipExtensionEntity;
    const config = (service as any).buildExtensionsConfig([ext]);
    expect(config).toContain('[1000]'); 
    expect(config).toContain('type = endpoint');
    expect(config).toContain('[1000-auth]');
    expect(config).toContain('password = pwd');
  });

  it('generatePjsipConfig with empty list returns only the global transport section', () => {
    const config = (service as any).buildExtensionsConfig([]);
    expect(config.trim()).toBe('; auto-generated by callytics — do not edit manually');
  });

  it('generateTrunkConfig with a trunk record produces registration and endpoint section', () => {
    const trunk = { id: 1, name: 't1', host: 'provider.com', port: 5060, username: 'user', enabled: true } as SipTrunkEntity;
    const config = (service as any).buildTrunksConfig([trunk]);
    expect(config).toContain('[trunk-1]');
    expect(config).toContain('[trunk-1-reg]');
    expect(config).toContain('type = registration');
    expect(config).toContain('server_uri = sip:provider.com');
  });

  it('AMI reload command is called after config is written', async () => {
    const spyWrite = jest.spyOn(service, 'writeExtensionsConfig').mockResolvedValue();
    const spyReload = jest.spyOn(service as any, 'sendAmiCommand').mockResolvedValue(undefined);
    
    await service.syncExtensions([]);
    
    expect(spyWrite).toHaveBeenCalled();
    expect(spyReload).toHaveBeenCalledWith('module reload res_pjsip.so');
  });

  it('if AMI reload throws, the error is caught and not swallowed silently', async () => {
    jest.spyOn(service, 'writeExtensionsConfig').mockResolvedValue();
    jest.spyOn(service as any, 'sendAmiCommand').mockRejectedValue(new Error('AMI dead'));
    const loggerSpy = jest.spyOn((service as any).logger, 'error').mockImplementation(() => {});

    await expect(service.syncExtensions([])).resolves.not.toThrow();
    expect(loggerSpy).toHaveBeenCalledWith(expect.stringContaining('failed'), expect.any(Error));
  });
});
