[modules]
autoload = no

load = res_http_websocket.so
load = res_ari.so
load = res_ari_applications.so
load = res_ari_channels.so
load = res_ari_endpoints.so
load = res_ari_events.so
load = res_ari_model.so
load = res_ari_playbacks.so
load = res_ari_recordings.so
load = app_stasis.so
load = pbx_config.so
load = res_pjsip.so
load = chan_pjsip.so
load = res_pjsip_endpoint_identifier_user.so
load = res_rtp_asterisk.so
load = manager.so
load = codec_ulaw.so
load = format_wav.so
