[modules]
autoload = yes
preload => res_musiconhold.so

[global]

noload => res_snmp.so
noload => res_config_ldap.so
noload => res_config_pgsql.so
noload => res_config_mysql.so
noload => chan_skinny.so
noload => chan_mgcp.so
noload => chan_unistim.so
noload => res_adsi.so
noload => app_adsiprog.so
noload => app_getcpeid.so
