[global]
type = global
endpoint_identifier_order = username,ip,anonymous

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5080
#include pjsip_relay.conf

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5080

[test-phone-auth]
type = auth
auth_type = userpass
username = test-phone
password = test1234

[test-phone]
type = aor
max_contacts = 1
remove_existing = yes
qualify_frequency = 30

[test-phone]
type = endpoint
transport = transport-udp
context = callytics-inbound
disallow = all
allow = ulaw
allow = alaw
aors = test-phone
auth = test-phone-auth
direct_media = no
force_rport = yes
rewrite_contact = yes

[callytics-endpoint-template](!)
type = endpoint
transport = transport-udp
context = callytics-inbound
disallow = all
allow = ulaw
allow = alaw
direct_media = no
force_rport = yes
rewrite_contact = yes
media_address = 206.189.155.255
rtp_symmetric = yes

#include pjsip_extensions_relay.conf

#include pjsip_callytics_extensions.conf
#include pjsip_callytics_trunks.conf
