[global]
type = global
endpoint_identifier_order = username,ip,anonymous

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[test-phone]
type = endpoint
transport = transport-udp
context = callytics-inbound
disallow = all
allow = ulaw
aors = test-phone
direct_media = no

[test-phone]
type = aor
max_contacts = 1
remove_existing = yes
